### PR TITLE
Adding support for Surrogate-Key purging.

### PR DESCRIPTION
**Pull request by lukebussey**
This pull adds support for [Surrogate-Key](https://www.fastly.com/blog/surrogate-keys-part-1) purging.

I left out the test as I couldn't get them to work. Checkout the errors [here](https://gist.github.com/lukebussey/b2bd3502774c4f1f7586).

Thanks!

### CODE REVIEW

**Comment by lukebussey** [comment]
Any chance of getting this merged in?

**Comment by coen-hyde** [comment]
@lukebussey Thanks for this. I've added you as a contributor. If you can get the tests working and tests for this, that would be awesome. I don't use Grunt anymore so I'm looking for someone else to maintain this package.

**Comment by lukebussey** [comment]
Thanks, I'm more than happy to maintain it.

**Comment by coen-hyde** [comment]
@lukebussey Great! Let me know if you need anything.

**Pull request merged**
